#!/bin/bash
# store arguments in a special array
args=("$@")
# get number of elements
ELEMENTS=${#args[@]}
SCRIPT=""

# echo each element in array
# for loop
for (( i=0;i<$ELEMENTS;i++)); do
    SCRIPT+=" ${args[${i}]}"
done

php "$( dirname "${BASH_SOURCE[0]}" )/bin/forker.php" $SCRIPT
